updating termserver deploy & backup

diff --git a/roles/IHTSDO.termserver/templates/snowowl_hot_backup_mysql.sh.j2 b/roles/IHTSDO.termserver/templates/snowowl_hot_backup_mysql.sh.j2
--- a/roles/IHTSDO.termserver/templates/snowowl_hot_backup_mysql.sh.j2
+++ b/roles/IHTSDO.termserver/templates/snowowl_hot_backup_mysql.sh.j2
@@ -49,7 +49,7 @@ RETRY_WAIT_MINUTES=5
 backup_dir="{{ backup_dir }}"
 
 # The dir where zips go
-zip_dir="{{ zip_dir }}"
+zip_dir="{{ backup_zip_dir }}"
 
 # The working directory and the resulting archive file prefix
 ARCHIVE_PREFIX="snowowl_$(hostname -s)_$CURRENT_DATE"
@@ -57,8 +57,8 @@ ARCHIVE_PREFIX="snowowl_$(hostname -s)_$CURRENT_DATE"
 # The absolute path to the above
 ABSOLUTE_ARCHIVE_PREFIX="$zip_dir/$ARCHIVE_PREFIX"
 
-# The resources folder within the ABSOLUTE_ARCHIVE_PREFIX
-ABSOLUTE_ARCHIVE_RESOURCES="$ABSOLUTE_ARCHIVE_PREFIX/resources"
+# The indexes folder within the ABSOLUTE_ARCHIVE_PREFIX
+ABSOLUTE_ARCHIVE_INDEXES="$ABSOLUTE_ARCHIVE_PREFIX/{{ term_serv_indexes_dir }}"
 
 # The base URL of the REST services to use
 BASE_URL="{{ base_url }}"
@@ -138,7 +138,7 @@ backup_repository_index_version() {
 	
 	# The returned REST message will contain the list of files (one per each line), which we pass to xargs.
 	if [ ! -z "$CURL_MESSAGE" ]; then
-		echo "$CURL_MESSAGE" | xargs --delimiter='\n' --max-lines=1 cp --verbose --parents --target-directory="$ABSOLUTE_ARCHIVE_RESOURCES" || unlock_repository_and_exit "Couldn't copy files for version $VERSION of repository $REPOSITORY. Exiting with error."
+		echo "$CURL_MESSAGE" | xargs --delimiter='\n' --max-lines=1 cp --verbose --parents --target-directory="$ABSOLUTE_ARCHIVE_INDEXES" || unlock_repository_and_exit "Couldn't copy files for version $VERSION of repository $REPOSITORY. Exiting with error."
 	fi
 
 	# Return to the initial directory.
@@ -238,7 +238,7 @@ backup_supporting_index_snapshot() {
 	fi
 	
 	if [ ! -z "$CURL_MESSAGE" ]; then
-		echo "$CURL_MESSAGE" | xargs --delimiter='\n' --max-lines=1 cp --verbose --parents --target-directory="$ABSOLUTE_ARCHIVE_RESOURCES" || unlock_repository_and_exit "Couldn't copy files for snapshot $SNAPSHOT of supporting index $INDEX. Exiting with error."
+		echo "$CURL_MESSAGE" | xargs --delimiter='\n' --max-lines=1 cp --verbose --parents --target-directory="$ABSOLUTE_ARCHIVE_INDEXES" || unlock_repository_and_exit "Couldn't copy files for snapshot $SNAPSHOT of supporting index $INDEX. Exiting with error."
 	fi
 	
 	# Return to the initial directory.
@@ -313,7 +313,7 @@ main() {
 
 	echo_date "Create backup destination directory '$ABSOLUTE_ARCHIVE_PREFIX'."
 	mkdir -pv "$ABSOLUTE_ARCHIVE_PREFIX" || error_exit "Couldn't create directory '$ABSOLUTE_ARCHIVE_PREFIX'. Exiting with error."
-	mkdir -pv "$ABSOLUTE_ARCHIVE_RESOURCES" || error_exit "Couldn't create directory '$ABSOLUTE_ARCHIVE_RESOURCES'. Exiting with error."
+	mkdir -pv "$ABSOLUTE_ARCHIVE_INDEXES" || error_exit "Couldn't create directory '$ABSOLUTE_ARCHIVE_INDEXES'. Exiting with error."
 	echo_date "Starting backup; sending message to connected users."
 	send_message "Write access to repositories will be disabled while the system creates a backup in $INITIAL_WAIT_MINUTES minutes."
 	
