refset install, backup & restore

diff --git a/roles/IHTSDO.refset_mysql_backup/templates/backup_refset_s3.sh.j2 b/roles/IHTSDO.refset_mysql_backup/templates/backup_refset_s3.sh.j2
--- a/roles/IHTSDO.refset_mysql_backup/templates/backup_refset_s3.sh.j2
+++ b/roles/IHTSDO.refset_mysql_backup/templates/backup_refset_s3.sh.j2
@@ -24,6 +24,8 @@ fi
 # The starting directory
 backup_dir={{ refset_backup_dir }}
 
+refset_index_dir={{refset_indexBase_dir}}
+
 # The dir where zips go
 tmp_backup_dir=$backup_dir/tmp
 
@@ -54,14 +56,15 @@ main() {
 	echo_date "Create backup destination directory '$ABSOLUTE_ARCHIVE_PREFIX'."
 	mkdir -pv "$ABSOLUTE_ARCHIVE_PREFIX" || error_exit "Couldn't create directory '$ABSOLUTE_ARCHIVE_PREFIX'. Exiting with error."
 	echo_date "Starting backup"
+	copyfromdatadir
 	echo_date "dumping mysql..."
     mysql_dump &
-    #copyfromdatadir
     wait
 	echo_date "ARCHIVE_PREFIX.zip = $ARCHIVE_PREFIX.zip"
 	echo_date "ARCHIVE_PREFIX = $ARCHIVE_PREFIX"
 	cd "$tmp_backup_dir"
-	zip --recurse-paths --move --test "$ARCHIVE_PREFIX.zip" "$ARCHIVE_PREFIX" || error_exit "Archive creation failed; the backup is incomplete. Exiting with error."
+	tar  -zcf "$ARCHIVE_PREFIX.tar.gz" "$ARCHIVE_PREFIX" || error_exit "Archive creation failed; the backup is incomplete. Exiting with error."
+	#zip --recurse-paths --move --test "$ARCHIVE_PREFIX.zip" "$ARCHIVE_PREFIX" || error_exit "Archive creation failed; the backup is incomplete. Exiting with error."
 	
 	echo_date "Finished successfully."
         if [ -f ~/.aws/config ] && [ "$s3_backup_dir" != "" ];
@@ -78,9 +81,10 @@ echo_date "dumping mysql...to $ABSOLUTE_ARCHIVE_PREFIX/{{ refset_dump_filename }
  
 }
 
-#copyfromdatadir(){
-#cp -R refset_data_dir $ABSOLUTE_ARCHIVE_PREFIX
-#}
+copyfromdatadir(){
+echo_date "copying $refset_index_dir...to $ABSOLUTE_ARCHIVE_PREFIX"
+cp -R $refset_index_dir $ABSOLUTE_ARCHIVE_PREFIX
+}
 
 mkbkdir(){
 # first delete if there
@@ -97,7 +101,7 @@ echo "s3_backup_dir = "$s3_backup_dir;
 #then
 echo "Transferring backup to AWS S3";
 cd $tmp_backup_dir
-for i in *; do /usr/bin/aws s3 cp $i $s3_backup_dir_full $s3_backup_region; done
+for i in *.gz; do /usr/bin/aws s3 cp $i $s3_backup_dir_full $s3_backup_region; done
 echo "Backup transferred";
 echo "Backup process complete";
 #fi
